package com.resequencetwin.control.stream

import io.micrometer.core.instrument.FunctionCounter
import io.micrometer.core.instrument.Gauge
import io.micrometer.core.instrument.MeterRegistry
import io.micrometer.core.instrument.binder.MeterBinder
import org.springframework.stereotype.Component

/**
 * Binds live PBS state machine KPIs to Micrometer meters, making them available at
 * `/actuator/prometheus` (and any other registered registry).
 *
 * ## Design
 * [LivePbsProcessor] is the **single source of truth**. Every meter lambda reads
 * [LivePbsProcessor.snapshot] freshly on each scrape — no parallel counters are maintained here.
 * [LivePbsProcessor.snapshot] is `@Synchronized` and cheap (O(lanes)).
 *
 * ## Meter conventions
 * - **FunctionCounters** (`pbs.*.total`): cumulative, monotonically increasing values aligned with
 *   the Prometheus `_total` naming convention. The underlying values come from [LiveSnapshot]
 *   counters (`releases`, `colourChanges`, `rejected`, `duplicates`, `outOfOrder`, and
 *   `assemblyOutSize`). Use `rate(...)` in Grafana/PromQL to derive throughput.
 * - **Gauges** (`pbs.*`): current state that can go up or down — lane occupancy, deferred-buffer
 *   size, and number of currently blocked lanes.
 *
 * ## Honesty note
 * These metrics observe a **SYNTHETIC stream** generated by the S3 Python producer for this PoC.
 * They are not sourced from a real production plant floor; they demonstrate the telemetry
 * architecture, not actual manufacturing throughput.
 *
 * Spring Boot auto-detects [MeterBinder] beans and calls [bindTo] during actuator startup.
 *
 * @param processor the shared [LivePbsProcessor] bean — injected by Spring.
 */
@Component
class LiveMetrics(
    private val processor: LivePbsProcessor,
) : MeterBinder {

    override fun bindTo(registry: MeterRegistry) {
        // Read lane ids once at bind time from the initial snapshot.
        // The topology is static (fixed at startup from pbs.lanes property), so this is safe.
        val laneIds: List<String> = processor.snapshot().laneOccupants.keys.toList()

        // ── FunctionCounters (cumulative, Prometheus _total convention) ───────────
        FunctionCounter.builder("pbs.releases.total", processor) { it.snapshot().releases.toDouble() }
            .description("Total number of bodies released to assembly")
            .baseUnit("bodies")
            .register(registry)

        FunctionCounter.builder("pbs.colour.changes.total", processor) { it.snapshot().colourChanges.toDouble() }
            .description("Total number of consecutive-release colour switches")
            .baseUnit("changes")
            .register(registry)

        FunctionCounter.builder("pbs.rejected.total", processor) { it.snapshot().rejected.toDouble() }
            .description("Total number of rejected events (validation failures or unknown lanes)")
            .baseUnit("bodies")
            .register(registry)

        FunctionCounter.builder("pbs.duplicates.total", processor) { it.snapshot().duplicates.toDouble() }
            .description("Total number of duplicate events (same eventId seen more than once)")
            .baseUnit("bodies")
            .register(registry)

        FunctionCounter.builder("pbs.out.of.order.total", processor) { it.snapshot().outOfOrder.toDouble() }
            .description("Total number of events received with a stale (out-of-order) sequence number")
            .baseUnit("bodies")
            .register(registry)

        // pbs.assembly.out is a FunctionCounter (not a gauge) because the assembly buffer is
        // append-only in this synthetic PoC — bodies released to it are never removed.
        // assemblyOutSize is therefore monotonically non-decreasing, making a Prometheus counter
        // (and rate(...) queries) the correct semantic model.
        FunctionCounter.builder("pbs.assembly.out.total", processor) { it.snapshot().assemblyOutSize.toDouble() }
            .description(
                "Cumulative running total of bodies released to the assembly buffer. " +
                "The buffer is append-only in this synthetic PoC (no drain), so this value " +
                "is monotonically non-decreasing. Use rate(pbs_assembly_out_total[...]) in " +
                "Grafana instead of delta() on a gauge."
            )
            .baseUnit("bodies")
            .register(registry)

        // ── Gauges (current state, can increase or decrease) ─────────────────────
        Gauge.builder("pbs.buffered", processor) { it.snapshot().buffered.toDouble() }
            .description("Current number of bodies in the deferred buffer (awaiting lane availability)")
            .baseUnit("bodies")
            .register(registry)

        Gauge.builder("pbs.blocked.lanes", processor) { it.snapshot().blockedLanes.size.toDouble() }
            .description("Current number of lanes in the blocked state")
            .baseUnit("lanes")
            .register(registry)

        // Per-lane occupancy — one gauge per lane id, tagged with lane="<id>"
        for (laneId in laneIds) {
            Gauge.builder("pbs.lane.occupancy", processor) { p ->
                p.snapshot().laneOccupants[laneId]?.size?.toDouble() ?: 0.0
            }
                .tag("lane", laneId)
                .description("Current number of bodies occupying lane $laneId")
                .baseUnit("bodies")
                .register(registry)
        }
    }
}
